export const ADD_FAVORITE = 'ADD_FAVORITE'
export const FETCH_DATA = 'FETCH_DATA'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'   
export const SET_TEAM = 'SET_TEAM' 
export const SET_DETAIL = 'SET_DETAIL'
export const SET_SEARCH = 'SET_SEARCH'
export const SET_FILTERED_TEAMS = 'SET_FILTERED_TEAMS'